name: Call API on Schedule

on:
  workflow_call:
    inputs:
      api_url:
        required: true
        type: string
      http_method:
        required: false
        type: string
        default: 'GET'
      request_body:
        required: false
        type: string
        default: ''
    secrets:
      api_token:
        required: true

jobs:
  trigger-api:
    name: Trigger API Request
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Trigger API Request
        id: api_request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ inputs.api_url }}
          method: ${{ inputs.http_method }}
          customHeaders: '{"X-Api-Key": "${{ secrets.api_token }}", "Content-Type": "application/json"}'
          data: ${{ inputs.request_body }}
          timeout: 300000 

      - name: Log Response
        if: success()
        run: |
         echo "TriggerId = ${{ fromJson(steps.api_request.outputs.response).responsePayload.triggerId }}"
         echo "Response = ${{ steps.api_request.outputs.response }}"

      - name: Check API Response
        run: |
          STATUS_CODE=${{ fromJson(steps.api_request.outputs.response).status }}
          if [[ "$STATUS_CODE" -ge 400 ]]; then
            echo "❌ API call failed with status $STATUS_CODE"
            exit 1
          else
            echo "✅ API triggered successfully"
          fi
