name: "Concatenate Prefix with Environment"

on:
  workflow_call:
    inputs:
      environment:
        description: "Specify environment (dev, stage, prod)"
        required: true
        type: string
      mapping:
        description: "JSON string containing key-prefix pairs"
        required: true
        type: string

    outputs:
      result:
        description: "Final JSON with concatenated values"
        value: ${{ steps.process.outputs.result }}

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Convert Mapping and Concatenate
        id: process
        run: |
          echo "Processing mapping: ${{ inputs.mapping }}"
          result=$(echo '${{ inputs.mapping }}' | jq --arg env "${{ inputs.environment }}" 'with_entries(.value |= . + $env)')
          echo "result=$result" >> "$GITHUB_OUTPUT"
