name: Example Reusable Schedule
on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM
    - cron: '0 18 * * 6' # Saturday at 6 PM
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/Setup-Env.yml

  test_config:
    name: Test Reusable Configuration
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Show Results from Setup
        run: |
          echo "=== Variables from Setup-Env ==="
          echo '${{ needs.setup.outputs.variables }}' | jq .

      - name: Use Configuration
        run: |
          variables='${{ needs.setup.outputs.variables }}'
          
          # Extract specific values
          environment=$(echo "$variables" | jq -r '.environment // "unknown"')
          service_name=$(echo "$variables" | jq -r '.service_name // "unknown"')
          
          echo "Environment: $environment"
          echo "Service: $service_name"
