name: Update Run Name
description: Update the display name (run-name) of the currently running workflow run

inputs:
  name:
    description: New run name to set
    required: true
  dry_run:
    description: If 'true', do not call the API; only print what would be updated
    required: false
    default: 'false'
  token:
    description: GitHub Token
    required: true

outputs:
  name:
    description: The run name that was attempted/set
    value: ${{ steps.update.outputs.name }}

runs:
  using: composite
  steps:
    - id: update
      name: Update run name
      shell: bash
      run: |
        set -euo pipefail

        name='${{ inputs.name }}'
        dry='${{ inputs.dry_run }}'
          token='${{ inputs.token }}'

        if [ -z "$name" ]; then
          echo "Error: input 'name' is required." >&2
          exit 1
        fi

        repo="${GITHUB_REPOSITORY}"
        run_id="${GITHUB_RUN_ID}"

        echo "Target run: ${repo}#${run_id}"
        echo "New name: ${name}"

        if [ "${dry,,}" = "true" ]; then
          echo "Dry-run enabled; skipping API call."
        else
            # Use curl to patch the run name
            api_url="https://api.github.com/repos/${repo}/actions/runs/${run_id}"
            response=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH "$api_url" \
              -H "Authorization: Bearer $token" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\": \"$name\"}")
            if [ "$response" != "200" ]; then
              echo "Failed to update run name via HTTP (status $response)" >&2
              exit 1
            fi
            echo "Run name updated successfully."
        fi

        echo "name=$name" >> "$GITHUB_OUTPUT"