name: 'Java Build and Test'
description: 'Build and test a Java project.'
inputs:
  java_version:
    description: 'Java version'
    required: false
    default: '17'
  working_directory:
    description: 'Directory where the code resides'
    required: false
    default: '.'
  command:
    description: 'Command to run (e.g., mvn clean test)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: maven
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
        mvn -version
    - name: Run Build and Test Command
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "Running: ${{ inputs.command }}"
        ${{ inputs.command }}
    - name: Upload Java Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: java-test-results
        path: ${{ inputs.working_directory }}/target/surefire-reports
    - name: Check Java Build Status
      id: check
      run: |
        echo "✅ Java Build and Tests Successful"
        echo "status=success" >> "$GITHUB_OUTPUT"
