name: 'Sync Auth0 Tenants'
description: 'Sync data between Auth0 tenants using Auth0 Deploy CLI and a Python processing script.'
inputs:
  branch_name:
    description: 'Branch to checkout'
    required: false
    default: 'main'

secrets:
  source_config:
    required: true
  dest_config:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository | Branch ${{ inputs.branch_name }}
      uses: actions/checkout@v4
      with:
        repository: nabarun-ngo/ngo-nabarun-templates
        ref: ${{ inputs.branch_name }}
    - name: Install Auth0 Deploy CLI
      run: |
        npm install -g auth0-deploy-cli@latest
        a0deploy --version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Create JSON files from secret
      run: |
        echo '${{ secrets.source_config }}' > auth0-source.json
        echo '${{ secrets.dest_config }}' > auth0-target.json
    - name: Export from Source Tenant
      run: |
        a0deploy export -c auth0-source.json -f yaml -o ./exported
        echo "Files in the './exported' directory and subdirectories:"
        find ./exported -type f -print
    - name: Upload Raw Tenant File
      uses: actions/upload-artifact@v4
      with:
        name: Raw Tenant Folder
        path: ./exported
    - name: Run Python script to process Auth0 data
      run: python scripts/auth0/process_auth0_v2.py auth0-source.json ./exported/tenant.yaml
    - name: Upload Processed Tenant File
      uses: actions/upload-artifact@v4
      with:
        name: Processed Tenant File
        path: ./exported/tenant.yaml
    - name: Deploy to Target Tenant
      run: |
        echo "Files in the './exported' directory and subdirectories:"
        find ./exported -type f -print
        a0deploy import -c auth0-target.json -f yaml -i ./exported/tenant.yaml
