name: Call API

on:
  workflow_call:
    inputs:
      api_url:
        required: true
        type: string
      http_method:
        required: false
        type: string
        default: 'GET'
      request_body:
        required: false
        type: string
        default: ''
    secrets:
      api_token:
        required: false

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Trigger API Request
        id: api_request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ inputs.api_url }}
          method: ${{ inputs.http_method }}
          headers: '{"X-Api-Key": "${{ secrets.api_token }}", "Content-Type": "application/json"}'
          body: ${{ inputs.request_body }}
          responseFile: response.json

      - name: Log Response
        if: success()
        run: cat response.json

      - name: Check API Response
        run: |
          STATUS_CODE=$(jq -r '.statusCode' response.json)
          if [[ "$STATUS_CODE" -ge 400 ]]; then
            echo "❌ API call failed with status $STATUS_CODE"
            exit 1
          else
            echo "✅ API triggered successfully"
          fi
