name: Auth0 Sync Data v2
on:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default : 'main'
      
    secrets:
      source_config:
        required: true
      dest_config:
        required: true
        
jobs:
  sync_data:
    name: 'Sync Data between Auth0'
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout repository | Branch ${{ inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          repository: nabarun-ngo/ngo-nabarun-templates
          ref: ${{ inputs.branch_name }}

      - name: Install Auth0 Deploy CLI
        run: npm install -g auth0-deploy-cli

      - name: Create JSON files from secret
        run: |
          echo '${{ secrets.source_config }}' > auth0-source.json
          echo '${{ secrets.dest_config }}' > auth0-dest.json

      - name: Export from Source Tenant
        run: |
          a0deploy export -c auth0-source.json -f yaml -o ./exported

      - name: Run Bash Script to Process Auth0 Data
        run: |
          chmod +x scripts/process-auth0.sh
          ./scripts/process-auth0.sh auth0-source.json auth0-target.json ./exported/tenant.yaml

      - name: Results
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: ./exported/tenant.yaml

      # - name: Deploy to Target Tenant
      #   run: |
      #     a0deploy import -c auth0-target.json -f yaml -i ./exported
