name: Auth0 Import Data from Google Drive
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      target_folder:
        required: true
        type: string
    secrets:
      auth0_secrets:
        required: true
jobs:
  build_jar:
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Build-JAR.yml@main
    with:
      branch_name : ${{ inputs.branch_name }}
      target_folder: ${{ inputs.target_folder }}
  run_jar:
    name: 'Run JAR'
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
     - name: Execute Jar
       run: |
          java -jar ${{ needs.build_jar.outputs.jar_path }}
