name: Auth0 Sync Data v2
on:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default : 'main'
      
    secrets:
      source_config:
        required: true
      dest_config:
        required: true
        
jobs:
  sync_data:
    name: 'Sync Data between Auth0'
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout repository | Branch ${{ inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          repository: nabarun-ngo/ngo-nabarun-templates
          ref: ${{ inputs.branch_name }}

      - name: Install Auth0 Deploy CLI
        run: npm install -g auth0-deploy-cli

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create JSON files from secret
        run: |
          echo '${{ secrets.source_config }}' > auth0-source.json
          echo '${{ secrets.dest_config }}' > auth0-target.json

      - name: Export from Source Tenant
        run: |
          a0deploy export -c auth0-source.json -f yaml -o ./exported

      - name: Upload Raw Tenant File
        uses: actions/upload-artifact@v4
        with:
          name: Raw Tenant File
          path: ./exported/tenant.yaml
          
      - name: Run Python script to process Auth0 data
        run: python scripts/auth0/process_auth0.py auth0-source.json auth0-target.json ./exported/tenant.yaml

      - name: Upload Processed Tenant File
        uses: actions/upload-artifact@v4
        with:
          name: Processed Tenant File
          path: ./exported/tenant.yaml

      - name: Deploy to Target Tenant
        run: |
          a0deploy import -c auth0-target.json -f yaml -i ./exported
