name: Auth0 Import Data
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      source: # Options 'google_drive', 'repository'
        required: true
        type: string
      auth0_import_tenant:
        required: true
        type: string
      auth0_resource_server:
        required: true
        type: string
      input_file:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      target_folder:
        required: false
        type: string
        default: 'target'
      dry_run:
        required: false
        type: boolean
        default: false
      
    secrets:
      auth0_secrets:
        required: true
      gcp_service_account:
        required: false

jobs:
  import_data:
    name: 'Import Data to Auth0'
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout repository | Branch ${{ inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java_version }} 
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-   
        
      - name: Build with Maven
        run: |
          mvn clean package
          
      - name: Get JAR file path
        id: get-jar-path
        run: |
          JAR_PATH=$(find ${{ inputs.target_folder }} -name "*.jar" | grep -v "sources.jar" | grep -v "javadoc.jar")
          echo "jar_path=${JAR_PATH}" >> $GITHUB_ENV
          echo "JAR file path: ${JAR_PATH}"
          
      - name: Download file ${{ inputs.input_file }} from Google Drive
        uses: k0staa/download-gdrive-file-action@v1
        if: ${{ inputs.source == 'google_drive' }}
        with:
          service-account-key-json: ${{ secrets.gcp_service_account }}
          download-file-name: ${{ inputs.input_file }}

      - name: Import Data to Auth0 from ${{ inputs.source }}
        if: ${{ inputs.dry_run == false }}
        run: |
          java -jar ${{ env.jar_path }} auth0-import-data -d ${{ inputs.auth0_import_tenant }} -i ${{ inputs.input_file }} -r ${{ inputs.auth0_resource_server }} -c '${{ secrets.auth0_secrets }}'
      
      - name: Dry Run Variables Output
        if: ${{ inputs.dry_run == true }}
        run: |
          echo "Dry run mode enabled. Variables:"
          echo "Source: ${{ inputs.source }}"
          echo "Auth0 Import Tenant: ${{ inputs.auth0_import_tenant }}"
          echo "Input File: ${{ inputs.input_file }}"
          echo "Auth0 Resource Server: ${{ inputs.auth0_resource_server }}"
          
      - name: Dry run Verify Files
        if: ${{ inputs.dry_run == true }}
        run: |
          echo "Files in the root directory recursively:"
          find / -type f
