name: Auth0 Import Data from Google Drive
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      target_folder:
        required: true
        type: string
    secrets:
      auth0_secrets:
        required: true
      gcp_service_account:
        required: true

jobs:
  run_jar:
    name: 'Download from GCP and Build JAR'
    runs-on: ubuntu-latest
    steps:
      - name: Download file X from Google Drive to default (./) directory
        uses: k0staa/download-gdrive-file-action@v1
        with:
          service-account-key-json: ${{ secrets.gcp_service_account }}
          download-file-name: 'Documents/Application_Access_Management_v3.xlsx'
          
      - name: Checkout repository | Branch ${{ inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' 
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-   
        
      - name: Build with Maven
        run: |
          mvn clean package
          
      - name: Get JAR file path
        id: get-jar-path
        run: |
          JAR_PATH=$(find ${{ inputs.target_folder }} -name "*.jar" | grep -v "sources.jar" | grep -v "javadoc.jar")
          echo "jar_path=${JAR_PATH}" >> $GITHUB_ENV
          echo "JAR file path: ${JAR_PATH}"
