name: Build
on:
  workflow_call:
    inputs:
      platform:
        description: "Platform type (node, java, etc.)"
        required: true
        type: string
      repo:
        description: "Repository to clone"
        required: false
        type: string
      branch:
        description: "Branch to checkout (e.g., main, stage)"
        required: false
        type: string
      command:
        description: "Command to run (e.g., npm run build, mvn clean test)"
        required: true
        type: string
      node_version:
        description: "Node.js version (for Node apps)"
        required: false
        type: string
        default: "20"
      java_version:
        description: "Java version (for Java apps)"
        required: false
        type: string
        default: "17"
      working_directory:
        description: "Directory where the code resides"
        required: false
        type: string
        default: "."


jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.working_directory }}

      - name: Node.js Build and Test
        if: inputs.platform == 'node'
        uses: nabarun-ngo/ngo-nabarun-templates/.github/actions/build-node
        with:
          node_version: ${{ inputs.node_version }}
          working_directory: ${{ inputs.working_directory }}
          command: ${{ inputs.command }}

      - name: Java Build and Test
        if: inputs.platform == 'java'
        uses: nabarun-ngo/ngo-nabarun-templates/.github/actions/build-java
        with:
          java_version: ${{ inputs.java_version }}
          working_directory: ${{ inputs.working_directory }}
          command: ${{ inputs.command }}
