name: Build and Test
on:
  workflow_call:
    inputs:
      platform:
        description: "Platform type (node, java, etc.)"
        required: true
        type: string
      repo:
        description: "Repository to clone"
        required: false
        type: string
      branch:
        description: "Branch to checkout (e.g., main, stage)"
        required: false
        type: string
      command:
        description: "Command to run (e.g., npm run build, mvn clean test)"
        required: true
        type: string
      node_version:
        description: "Node.js version (for Node apps)"
        required: false
        type: string
        default: "20"
      java_version:
        description: "Java version (for Java apps)"
        required: false
        type: string
        default: "17"
      working_directory:
        description: "Directory where the code resides"
        required: false
        type: string
        default: "."

    outputs:
      build_status:
        description: "Build and Test Status"
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    name: Build and Test ${{ inputs.platform }}
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.working_directory }}

  node:
    name: Node.js Build and Test
    needs: build
    if: inputs.platform == 'node'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.working_directory }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Run Build and Test Command
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "Running: ${{ inputs.command }}"
          ${{ inputs.command }}

      - name: Upload Node Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-test-results
          path: ${{ inputs.working_directory }}/coverage

      - name: Check Node Build Status
        id: check
        run: |
          echo "✅ Node Build and Tests Successful"
          echo "status=success" >> "$GITHUB_OUTPUT"

  java:
    name: Java Build and Test
    needs: build
    if: inputs.platform == 'java'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.working_directory }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
          cache: maven

      - name: Run Build and Test Command
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "Running: ${{ inputs.command }}"
          ${{ inputs.command }}

      - name: Upload Java Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-test-results
          path: ${{ inputs.working_directory }}/target/surefire-reports

      - name: Check Java Build Status
        id: check
        run: |
          echo "✅ Java Build and Tests Successful"
          echo "status=success" >> "$GITHUB_OUTPUT"
