name: Create Tag & Release 
on:
  workflow_call:
     inputs:
      source_branch:
         required: false
         type: string
      pre_release_branches:
         required: false
         type: string
         default: 'staging,stage'
     outputs:
      tag_name:
        value: ${{ jobs.create_tag.outputs.tag_name }}
        
permissions:
      contents: write    
      
jobs:
  create_tag:
    name: 'Create Tag'
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}
      release_type: ${{ steps.tag_version.outputs.release_type }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         ref: ${{ inputs.source_branch }}
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: ${{ inputs.pre_release_branches }}
    
  create_release:
    name: 'Create Release'
    if: ${{ jobs.create_tag.outputs.release_type != 'patch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  
