name: Firebase Sync Data
on:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default: 'main'
      firebase_source_project:
        required: true
        type: string
      firebase_target_project:
        required: true
        type: string
    secrets:
      firebase_service_account_source:
        required: true
      firebase_service_account_target:
        required: true
        
jobs:
  sync_remote_config:
    name: 'Sync Data between Firebase Remote Config'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Export Remote Config from Source
        run: |
          echo '${{ secrets.firebase_service_account_source }}' > $HOME/source-firebase.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/source-firebase.json
          firebase projects:list --project=${{ inputs.firebase_source_project }}
          firebase remoteconfig:get --project=${{ inputs.firebase_source_project }} > remote-config.json

      - name: Upload Remote Config as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-config
          path: remote-config.json
          retention-days: 7  # Keep the file for 7 days

      - name: Import Remote Config to Target
        run: |
          echo '${{ secrets.firebase_service_account_target }}' > $HOME/target-firebase.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/target-firebase.json
          firebase projects:list --project=${{ inputs.firebase_target_project }}
          firebase remoteconfig:deploy --project=${{ inputs.firebase_target_project }} --config=remote-config.json
