name: Build and Deploy to Firebase Hosting
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo_owner_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      environment_url:
        required: false
        type: string
      firebase_project_id:
        required: true
        type: string
      npm_run_command:
        required: true
        type: string
    secrets:
      firebase_service_account:
        required: true
      repo_token:
        required: true
     
jobs:  
   build-and-deploy:
    name: 'Build Artifacts and Deploy to Firebase'
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Checkout repository | tag ${{ inputs.tag_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
          repository: '${{ inputs.repo_owner_name }}/${{ inputs.repo_name }}'

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ secrets.repo_token }}
          environment-url: ${{ inputs.environment_url }}
          environment: ${{ inputs.environment_name }}
          repo: ${{ inputs.repo_name }}
          owner: ${{ inputs.repo_owner_name }}
          
      - name: Update package.json version
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: '{"version": "${{ inputs.tag_name }}"}'
          
      - name: Build NPM
        run: ${{ inputs.npm_run_command }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.firebase_service_account }}'
          channelId: live
          projectId: ${{ inputs.firebase_project_id }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          token: ${{ secrets.repo_token }}
          environment-url: ${{ inputs.environment_url }}
          repo: ${{ inputs.repo_name }}
          owner: ${{ inputs.repo_owner_name }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          token: ${{ secrets.repo_token }}
          environment-url: ${{ inputs.environment_url }}
          repo: ${{ inputs.repo_name }}
          owner: ${{ inputs.repo_owner_name }}
 
  
  
