name: Build and Deploy to Firebase Hosting
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      firebase_project_id:
        required: true
        type: string
      is_prod_env:
        required: true
        type: boolean
    secrets:
      firebase_service_account:
        required: true
      github_token:
        required: true
jobs:  
   build-and-deploy-prod:
    name: 'Build Artifacts and Deploy to Firebase'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository | tag ${{ inputs.tag_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
          
      - name: Update package.json version
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: '{"version": "${{ inputs.tag_name }}"}'
          
      - name: Build NPM
        run: npm ci --legacy-peer-deps && npm run ${{ input.is_prod_env && "build" || "buildstage" }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.github_token }}'
          firebaseServiceAccount: '${{ secrets.firebase_service_account }}'
          channelId: live
          projectId: ${{ inputs.firebase_project_id }}
 
  
  
