name: Build and Deploy to GCP App Engine
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      target_folder:
        required: true
        type: string
      gcp_project_id:
        required: true
        type: string
      gae_app_yaml_path:
        required: false
        type: string
        default: 'app.yaml'
      gae_service_name:
        required: false
        type: string
        default: 'default'
      app_env:
        required: true
        type: string
      app_doppler_project_name:
        required: true
        type: string
      app_log_level:
        required: false
        type: string
        default: 'INFO'
    secrets:
      gcp_service_account:
        required: true
      app_doppler_service_token:
        required: true
jobs:
  build_jar:
    name: 'Checkout Repo and Build JAR'
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Build-JAR.yml@main
    with:
      branch_name : ${{ inputs.tag_name }}
      target_folder: ${{ inputs.target_folder }}
      files_to_copy: ${{ inputs.gae_app_yaml_path }}
      
  deploy_to_gcp:
    name: 'Deploy JAR to GCP App Engine'
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Setup Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          credentials_json: ${{ secrets.gcp_service_account }}
          export_default_credentials: true
        
      - name: Setup Application Variables
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        with:
          path: '${{ inputs.target_folder }}/${{ inputs.gae_app_yaml_path }}'
        env:
         ENVIRONMENT: ${{ inputs.app_env }} 
         DOPPLER_PROJECT_NAME: ${{ inputs.app_doppler_project_name }}
         DOPPLER_SERVICE_TOKEN: ${{ secrets.app_doppler_service_token }}  
         LOG_LEVEL: ${{ inputs.app_log_level }}
         VERSION: ${{ inputs.tag_name }}
         
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          credentials: ${{ secrets.gcp_service_account }}
          promote: true
          deliverables: ${{ needs.build_jar.outputs.jar_path }}
          flags: '--appyaml=${{ inputs.target_folder }}/${{ inputs.gae_app_yaml_path }}'
  
  clean_gcp_resources:
    runs-on: ubuntu-latest
    needs: [build_jar,deploy_to_gcp]
    steps:     
      - name: Encode Variable to Base64
        id: encode
        run: |
          ENCODED=$(echo '${{ secrets.gcp_service_account }}' | base64)
          echo 'GCP_SA_KEY_ENCODED<<EOF' >> $GITHUB_ENV
          echo "$ENCODED" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Delete GAE versions
        uses: vijayp23/delete-gae-version-action@1.0.0
        with:
          service-account: ${{ env.GCP_SA_KEY_ENCODED }}
          project-id: ${{ inputs.gcp_project_id }}
          service-name: ${{ inputs.gae_service_name }}
