name: JMeter Performance Test

# Mark this workflow as reusable
on:
  workflow_call:
    inputs:
      test-plan:
        description: 'Path to the JMeter test plan (.jmx)'
        required: true
        type: string
      target-url:
        description: 'Base URL of the application to test'
        required: true
        type: string
      threads:
        description: 'Number of virtual users'
        required: false
        type: number
        default: 10
      ramp-up:
        description: 'Ramp-up period in seconds'
        required: false
        type: number
        default: 10
      loops:
        description: 'Number of loops per user'
        required: false
        type: number
        default: 1

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.7.1.tgz
          tar -xzf apache-jmeter-5.7.1.tgz
          export PATH=$PWD/apache-jmeter-5.7.1/bin:$PATH

      - name: Run JMeter Test
        run: |
          # Export environment variable for target URL
          export TARGET_URL=${{ inputs.target-url }}
          
          # Run test in non-GUI mode
          ./apache-jmeter-5.7.1/bin/jmeter -n \
            -t ${{ inputs.test-plan }} \
            -Jthreads=${{ inputs.threads }} \
            -Jramp_up=${{ inputs.ramp-up }} \
            -Jloops=${{ inputs.loops }} \
            -l results.jtl -j jmeter.log

      - name: Generate HTML Report
        run: |
          ./apache-jmeter-5.7.1/bin/jmeter -g results.jtl -o jmeter-report

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: jmeter-report
