name: Publish to Github Packages
on:
  workflow_call:
     inputs:
      source_tag:
        required: true
        type: string
      package_manager:
         required: true
         type: string
      java_version:
         required: false
         type: string
         default: '17'
      server_id:
         required: false
         type: string
         default: 'github'

jobs:
  mvn_publish:
    name: Publish Maven Package
    if: ${{ inputs.package_manager == 'mvn' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.source_tag }}
        
    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        server-id: ${{ inputs.server_id }} # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Update POM version
      run: |
        # Remove the leading 'v' if present (e.g., v1.0.4 -> 1.0.4)
        version="${{ inputs.source_tag }}"
        version="${version#v}"
        echo "🔧 Setting POM version to: $version"
        mvn versions:set -DnewVersion=$version -DgenerateBackupPoms=false -DprocessAllModules=true
        mvn versions:commit
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}


    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: 'maven'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
    
    - name: Update POM version
      run: |
        # Remove the leading 'v' if present (e.g., v1.0.4 -> 1.0.4)
        version="${{ inputs.source_tag }}"
        version="${version#v}"
        echo "🔧 Setting POM version to: $version"
        mvn versions:set -DnewVersion=$version -DgenerateBackupPoms=false -DprocessAllModules=true
        mvn versions:commit
    
    - name: Build all modules
      run: mvn -B clean install
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish modules to GitHub Packages
      run: mvn -B deploy -DskipTests
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

