name: 'Redis Delete Keys'

on:
  workflow_call:
    inputs:
      key:
        description: "Specify a Redis key to delete (leave empty to delete all)"
        required: false
        type: string
        default: ''
    secrets:
      redis_host:
        description: 'Redis Host'
        required: true
      redis_port:
        description: 'Redis Port'
        required: true
      redis_password:
        description: 'Redis Password'
        required: true

jobs:
  delete-redis-key:
    runs-on: ubuntu-latest
    steps:
      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Delete Specific Redis Key
        if: ${{ inputs.key != '' }}
        run: redis-cli -h ${{ secrets.redis_host }} -p ${{ secrets.redis_port }} -a ${{ secrets.redis_password }} DEL "${{ inputs.key }}"

      - name: Clear Redis Cache (All Keys)
        if: ${{ inputs.key == '' }}
        run: redis-cli -h ${{ secrets.redis_host }} -p ${{ secrets.redis_port }} -a ${{ secrets.redis_password }} FLUSHALL
