name: 'Redis Ping Pong'

on:
  workflow_call:
    secrets:
      redis_host:
        description: 'Redis Host'
        required: true
      redis_port:
        description: 'Redis Port'
        required: true
      redis_password:
        description: 'Redis Password'
        required: true

jobs:
  redis-ping:
    runs-on: ubuntu-latest
    steps:
      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Ping Redis Server
        run: |
          response=$(redis-cli -h ${{ secrets.redis_host }} -p ${{ secrets.redis_port }} -a ${{ secrets.redis_password }} PING)
          echo "Redis response: $response"
          if [ "$response" != "PONG" ]; then
            echo "Redis did not respond with PONG"
            exit 1
          fi
