name: Run MongoDB Migration
on:
  workflow_call:
    inputs:
      script_file:
        required: true
        type: string
      source_db:
        required: true
        type: string
      dest_db:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      working_directory:
        required: false
        type: string
        default: 'migrations'
      repository_name:
        type: string
        required: false
      branch_name:
        type: string
        required: false
    secrets:
      MONGO_URI:
        required: true

jobs:
  run-migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Checkout repository | Branch ${{ inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_name }}
          ref: ${{ inputs.branch_name }}

      - name: Install MongoDB Shell
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Verify Files
        run: |
          echo "Files in the current directory and subdirectories:"
          find . -type f

      - name: Run MongoDB Migration
        working-directory: ${{ inputs.working_directory }}
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SOURCE_DB: ${{ inputs.source_db }}
          DEST_DB: ${{ inputs.dest_db }}
        run: mongosh "$MONGO_URI" ${{ inputs.script_file }}
