name: 'Set Inputs'
on:
  workflow_call:
    inputs:
      inputs:
        description: "All workflow_dispatch inputs as JSON string"
        type: string
        required: false
      client_payload:
        description: "repository_dispatch client payload as JSON string"
        type: string
        required: false
    outputs:
      variables:
        description: "Merged input variables as JSON"
        value: ${{ jobs.set_env.outputs.variables }}

jobs:
  set_env:
    runs-on: ubuntu-latest
    outputs:
      variables: ${{ steps.set_vars.outputs.variables }}
    steps:
      - name: Merge Inputs and Payload
        id: set_vars
        run: |
          # Read inputs
          inputs_json="${{ inputs.inputs }}"
          payload_json="${{ inputs.client_payload }}"

          # Determine which input to use
          if [[ ! -z "$payload_json" && "$payload_json" != "null" ]]; then
            final_data="$payload_json"
          else
            final_data="$inputs_json"
          fi

          echo "Final Merged Data: $final_data"

          # Set GitHub output
          echo "variables=$final_data" >> $GITHUB_OUTPUT
