name: 'Setup'
on:
  workflow_call:
    inputs:
      inputs:
        description: "All workflow_dispatch inputs as JSON string"
        type: string
        required: false
      client_payload:
        description: "repository_dispatch client payload as JSON string"
        type: string
        required: false
      script_path:
        description: "Path to shell script to execute (optional)"
        type: string
        required: false
    outputs:
      variables:
        description: "Merged input variables as JSON"
        value: ${{ jobs.set_env.outputs.variables }}

jobs:
  set_env:
    name : 'Set Variables'
    runs-on: ubuntu-latest
    outputs:
      variables: ${{ steps.set_vars.outputs.variables }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Schedule Configuration
        id: determine_config
        if: ${{ github.event_name == 'schedule' }}
        uses: ./.github/actions/determine-schedule-config

      - name: Resolve and Export Inputs
        uses: nabarun-ngo/ngo-nabarun-templates/.github/actions/resolve-inputs@main
        with:
          inputs: ${{ inputs.inputs }}
          client_payload: ${{ inputs.client_payload }}
          schedule_config_file: ${{ steps.determine_config.outputs.config_file }}

      - name: Print all environment variables
        shell: bash
        run: |
          echo "===== All Env Vars ====="
          env
          echo "========================"
          
      # This script will compute the workflow run-name and set it as output variable 'run_name'
      - name: Execute Shell Script
        if: ${{ inputs.script_path != '' }}
        id: execute_script
        run: |
          chmod +x ${{ inputs.script_path }}
          ${{ inputs.script_path }}

      - name: Print all environment variables
        shell: bash
        run: |
          echo "===== All Env Vars ====="
          env
          echo "========================"

      - name: Resolve and Export Inputs (Final)
        id: set_vars
        uses: nabarun-ngo/ngo-nabarun-templates/.github/actions/resolve-inputs@main
        with:
          update_from_env: true

