name: Reusable PR Description Updater

on:
  workflow_call:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string
      repository:
        description: "Repository (owner/repo)"
        required: true
        type: string
    secrets:
      token:
        required: true

  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: number
      repository:
        description: "Repository (owner/repo)"
        required: true
        type: string

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.token }}" | gh auth login --with-token

      - name: Fetch Commit Messages and Update PR Description
        run: |
          REPO="${{ inputs.repository }}"
          PR_NUMBER="${{ inputs.pr_number }}"
          COMMIT_MESSAGES=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json commits --jq '.commits[].messageHeadline' | sed 's/^/- /')
          echo "${COMMIT_MESSAGES}" > commits.md
          gh pr edit "$PR_NUMBER" --repo "$REPO" -F "-commits.md"
