name: "Caller Workflow"
on:
  workflow_dispatch:
    inputs:
      auth0_target_tenant:
        description: "Auth0 Target Tenant"
        required: true
        type: choice
        options:
          - DEV
          - STAGE
      firebase_sync_rc:
        description: "Sync Firebase"
        required: false
        default: false
        type: boolean

  repository_dispatch:
    types: [Trigger-Import-Sync-Data]

jobs:
  set_inputs:
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/set_env.yml@main
    with:
      inputs: ${{ toJson(inputs) }}
      client_payload: ${{ toJson(github.event.client_payload) }}

  use_variables:
    runs-on: ubuntu-latest
    needs: set_inputs
    steps:
      - name: Print Merged Variables
        run: echo '${{ needs.set_inputs.outputs.variables }}'
